services:
  aichhoernchen:
    image: ghcr.io/just-another-muensterhack/aichhoernchen-backend
    restart: always
    ports:
      - "8000:80"
    environment:
      DB_HOST: postgres
      DB_NAME: aichhoernchen
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: aichhoernchen
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  mc:
    image: quay.io/minio/mc
    entrypoint: >
      /bin/sh -c "
      /bin/bash -c 'while ! $((echo >/dev/tcp/minio/9000) &>/dev/null); do echo waiting for minio; sleep 3; done; echo minio healthcheck successful;';
      /usr/bin/mc mb minio/aihoernchen-bucket;
      /usr/bin/mc admin user add minio aichhoernchen aichhoernchen ;
      /usr/bin/mc admin policy attach minio readwrite --user aichhoernchen;
      exit 0;"

volumes:
    postgres_data:
    minio_data:
