services:
  aihoernchen:
    container_name: aihoernchen
    extra_hosts:
      - host.docker.internal:host-gateway
    init: true
    ports:
      - 8000:8000
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      - no_proxy="127.0.0.1,localhost"
      - NO_PROXY="127.0.0.1,localhost"
    env_file:
      - .env
      - path: local.env
        required: false
    volumes:
      - ..:/workspaces:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  postgres:
    image: postgres:18
    restart: always
    env_file:
      - .env
