# Generated by Django 5.2.6 on 2025-09-26 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundobject',
            name='deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='found_objects', to='finder.lostpropertyoffice'),
        ),
        migrations.AlterField(
            model_name='foundobject',
            name='finder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='found_object', to='finder.finder'),
        ),
        migrations.AlterField(
            model_name='lostpropertyoffice',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
