# Generated by Django 5.2.6 on 2025-09-26 14:56

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_alter_foundobject_deposit_alter_foundobject_finder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foundobject',
            name='finder',
        ),
        migrations.AddField(
            model_name='foundobject',
            name='finder_email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foundobject',
            name='finder_name',
            field=models.TextField(default=datetime.datetime(2025, 9, 26, 14, 56, 0, 475439, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foundobject',
            name='finder_phone',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foundobject',
            name='deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objects', to='finder.lostpropertyoffice'),
        ),
        migrations.DeleteModel(
            name='Finder',
        ),
    ]
