# Generated by Django 5.2.6 on 2025-09-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0003_remove_foundobject_finder_foundobject_finder_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundobject',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='foundobject',
            name='long',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='lostpropertyoffice',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='lostpropertyoffice',
            name='long',
            field=models.FloatField(),
        ),
    ]
