# Generated by Django 5.2.6 on 2025-09-26 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0004_alter_foundobject_lat_alter_foundobject_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundobject',
            name='deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='found_objects', to='finder.lostpropertyoffice'),
        ),
    ]
