# Generated by Django 5.2.6 on 2025-09-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0005_alter_foundobject_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundobject',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
