# Generated by Django 5.2.6 on 2025-09-27 13:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0006_foundobject_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundobject',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
